use crate::prelude::*;

/// Represents the order price limits for a trading symbol.
///
/// This struct contains the highest bid price (buyLmt) and lowest ask price (sellLmt)
/// for a given symbol, which define the order price limits for derivative or spot trading.
/// These limits are important for risk management and order validation.
#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct OrderPriceLimit {
    /// The trading pair symbol (e.g., "BTCUSDT").
    ///
    /// Identifies the specific instrument for which the price limits apply.
    /// Trading bots should verify this matches the requested symbol to ensure data integrity.
    pub symbol: String,

    /// The highest bid price allowed (buy limit) as a string.
    ///
    /// Represents the maximum price at which buy orders can be placed.
    /// Orders with prices above this limit will be rejected.
    /// Trading bots must ensure buy order prices do not exceed this limit.
    pub buy_lmt: String,

    /// The lowest ask price allowed (sell limit) as a string.
    ///
    /// Represents the minimum price at which sell orders can be placed.
    /// Orders with prices below this limit will be rejected.
    /// Trading bots must ensure sell order prices are not below this limit.
    pub sell_lmt: String,

    /// The timestamp in milliseconds when the price limits were last updated.
    ///
    /// Indicates when the price limit data was generated by Bybit's servers.
    /// Trading bots can use this to determine if the data is fresh enough for their strategies.
    pub ts: String,
}

/// The main response type for the order price limit API endpoint.
///
/// This is the top-level response structure returned by the `/v5/market/price-limit` endpoint.
pub type OrderPriceLimitResponse = BybitApiResponse<OrderPriceLimit>;
